### ISSUE TITLE
Queue integration

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/northstar-mobilecommonsd#2]
Right now, I'm testing everything using the `sync` queue adapter. That's obvs not a long term solution though, so we should think about how this would work in prod. Should this integrate with the Message Broker's existing queueing architecture (even though it's not messaging)? Should it run its own queue? 

:question:

**Comment by mshmsh5000** [comment]
If it's just a work queue and doesn't touch other systems, we could run this the way we do other Laravel apps, with a local Redis queue.

**Comment by DFurnes** [comment]
I think that seems good. That seems like the smallest dev & ops lift as well, which is always nice. :smile:

**Comment by mshmsh5000** [comment]
Totes. We might even be able to just deploy this on an existing Laravel app server -- will check with the authorities.

**Comment by deezone** [comment]
> even though it's not messaging

For what it's worth, there's lots going on in Message Broker (Quicksilver Land) that has nothing to do with messaging. For one, thousands of users are imported daily from our marketing partners.

**Comment by DFurnes** [comment]
@DeeZone Yes, hence asking if it makes sense in there! Much respect for all the infrastructure you've built up, and all the logging and monitoring and stuff that's built in. I just don't want to create more work for you or lump in things that might not belong. :smile:

**Comment by deezone** [comment]
The "respect" is more directed at you! Having a functional Luman app to reference is huge for potential Quicksilver applications. 

As for queues, I'd be interested in a quick chat to understand how the application works, how it may fail and the level of concern if it does fail. With these answered, determining if the effort to integrate into Quicksilver will be possible.

**Comment by DFurnes** [comment]
:bow:!

We just talked IRL and we're thinking that integrating this into the ~~Message Broker~~ Quicksilver queueing architecture could be a nice idea for a v1.1, since it'd be great to be able to easily monitor how many things are in the queue at any given time, etc.
