### ISSUE TITLE
Re-start unfinished time segments

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/northstar-mobilecommonsd#23]
A few time segments seem to have been abandoned when looking at the `php artisan mobilecommons:status` table. Let's restart those to see if we can finish them up.

**Comment by DFurnes** [comment]
It's not included in the base Lumen installation, but we can set up `artisan tinker` with [this](https://github.com/vluzrmos/lumen-tinker).

**Comment by DFurnes** [comment]
So two interesting updates here:

I was able to restart all the "missing" jobs by just running `php artisan queue:retry all`... because they weren't missing at all – they were stored in the failed jobs table. Duh! Taylor continues to be a god-damned hero. 🙌

A subset of these errors seem to have been caused because a maximum message size was exceeded and Amazon SQS refused to accept the job:

```
Next Aws\Sqs\Exception\SqsException: Error executing "SendMessage" on "https://sqs.us-east-1.amazonaws.com/389428637636/nsmcd-northstar"; AWS HTTP error: Client error: `POST https://sqs.us-east-1.amazonaws.com/389428637636/nsmcd-northstar` resulted in a `400 Bad Request` response:
<?xml version="1.0"?><ErrorResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/"><Error><Type>Sender</Type><Code>I (truncated...)
 InvalidParameterValue (client): One or more parameters are invalid. Reason: Message must be shorter than 262144 bytes.
```

I'm not 100% sure but I think when one user in a page of results fails to queue up, the entire `App\Jobs\LoadResultsFromMobileCommons` job is marked as failed & that's why those timeframes are getting dropped.

**Comment by weerd** [comment]
> Taylor continues to be a god-damned hero. 🙌

So say we all. 😉

**Comment by DFurnes** [comment]
These errors have been squashed! The backfill continues! 🚚
