### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by DFurnes** [DoSomethingArchive/northstar-mobilecommonsd#5]
This should be pretty straightforward, since this is _more or less_ a standard Laravel app. It may or may not need it's own queue (pending discussion in #2).

It will also need a cron job to [trigger Lumen's built-in scheduler](https://laravel.com/docs/5.2/scheduling#introduction):

```
* * * * * php /var/www/northstar-mobilecommonsd/current/artisan schedule:run >> /dev/null 2>&1
```

**Comment by deezone** [comment]
Playing `devils advocate` :smiling_imp: , why not use Jenkins? This would surface the job, provide a UI to easily check for monitoring? Is having it in version control really so valuable if it's not easy to keep an eye on the job?

**Comment by DFurnes** [comment]
@DeeZone I'd be open to that if it's easier. The artisan command just kicks off queued jobs, so I'm not sure we'd run into many situations where errors would be surfaced in the Jenkins logs though.

**Comment by deezone** [comment]
Is there any concern in how long the job takes? I often use the Jenkins interface to quickly determine the processing time of a job to identify bottlenecks.

**Comment by DFurnes** [comment]
Oh, I didn't know that Jenkins could track queued jobs. Yeah, that'd be super helpful to have. :+1:

**Comment by DFurnes** [comment]
This is done, thanks @sheyd!
